name: 🏗️ Build documentation

on:
  pull_request:
    branches: [ master ]
    paths:
      - pyproject.toml
      - ../../mytunes/**
      - docs/**

  workflow_dispatch:

  workflow_call:

permissions:
  contents: read

env:
  python-version: '3.12'

jobs:
  build:
    name: 📃 Build pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup - Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      - name: ⚙️ Setup - Pages
        uses: actions/configure-pages@v5

      - name: ⚙️ Setup - Install dependencies
        run: |
          sudo apt install graphviz
          pip install -e '.[docs]'

      - name: 🏗️ Sphinx build
        run: |
          make html
          make linkcheck

      - name: 📦 Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_build/html
